version: '3.9'
services:
  backend-app:
    build:
      context: .
      dockerfile: local.Dockerfile
    command: '/app/scripts/docker/local-run.sh'
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - './src:/app/src'
