version: "3"
services:
  express-typescript:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app-express-typescript"
    volumes:
      - .:/usr/src/app/
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
