name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version: v22.4.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Test
        run: npm run test